### ISSUE TITLE
Security vulnerability of 'kind-of' in 6.0.0.

### ISSUE THREAD

**Issue by buptliuhs** [inspect-js/is-data-descriptor#3]
https://www.npmjs.com/advisories/1490
![image](https://user-images.githubusercontent.com/3362360/80448714-462ebf80-8971-11ea-834e-d690de7a3d80.png)

Remediation: Upgrade to versions 6.0.3 or later.

**Comment by hthetiot** [comment]
PR with fix: https://github.com/jonschlinkert/is-data-descriptor/pull/4

**Comment by ljharb** [comment]
Fixed in #4 and #5.
